## Log.gd
## Project-wide error and warning helper.
##
## Wraps push_error() and push_warning() so that messages in the Output
## panel and Debugger include the caller's filename and line number on the
## same line as the message text:
##
##   ERROR: Arena.gd:142 some message here
##
## That format can be copy-pasted directly into a bug report as:
##   "when i run the project i get error Arena.gd:142 some message here"
##
## Usage anywhere in the project (no import needed — registered as autoload):
##   Log.err("something went wrong")
##   Log.warn("unexpected state")
##
## IMPORTANT — what this does NOT cover:
##   Runtime errors from the GDScript VM (null dereferences, type mismatches,
##   out-of-bounds, etc.) are generated by the engine itself and cannot be
##   intercepted or reformatted from GDScript. Those still appear in Godot's
##   default two-line format in the Debugger panel.
##
## get_stack() is a debug-only function stripped from release exports.
## In a release build the messages fall back to plain push_error/push_warning
## with no location prefix — acceptable since error reporting is a dev tool.

extends Node


## Log an error. Output in the Debugger/Output panel:
##   ERROR: FileName.gd:line message
static func err(message: String) -> void:
	var stack := get_stack()
	# stack[0] is this function; stack[1] is the site that called Log.err().
	if stack.size() > 1:
		var frame: Dictionary = stack[1]
		var file: String      = (frame.get("source", "?") as String).get_file()
		var line: int         = frame.get("line", 0)
		push_error("%s:%d %s" % [file, line, message])
	else:
		# Fallback: get_stack() unavailable (release build or bare top-level call).
		push_error(message)


## Log a warning. Output in the Debugger/Output panel:
##   WARNING: FileName.gd:line message
static func warn(message: String) -> void:
	var stack := get_stack()
	if stack.size() > 1:
		var frame: Dictionary = stack[1]
		var file: String      = (frame.get("source", "?") as String).get_file()
		var line: int         = frame.get("line", 0)
		push_warning("%s:%d %s" % [file, line, message])
	else:
		push_warning(message)
